version: '2'
services:
  medicalinspectionapplication-app:
    image: medicalinspectionapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://medicalinspectionapplication-postgresql:5432/MedicalInspectionApplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8585:8585
  medicalinspectionapplication-postgresql:
    extends:
      file: postgresql.yml
      service: medicalinspectionapplication-postgresql
